// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebSQLiteSample.Models;

#nullable disable

namespace WebSQLiteSample.Migrations
{
    [DbContext(typeof(JobDBContext))]
    [Migration("20241204050824_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebSQLiteSample.Models.JobData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Occupation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefecture")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobData");
                });
#pragma warning restore 612, 618
        }
    }
}
